[package]
name = "http_requests_v1"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mers = { path = "../../mers/" }
reqwest = { version = "0.11.16", features = ["blocking"] }
